/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LpRouteImport } from './routes/lp'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro-empresa'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CompanyRegistrationRouteImport } from './routes/Company-registration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrRouteImport } from './routes/_authenticated/pr'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConexoesRouteImport } from './routes/_authenticated/conexoes'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthTiktokCallbackRouteImport } from './routes/auth.tiktok.callback'
import { Route as ApiDebugBingAiTestRouteImport } from './routes/api/debug/bing-ai-test'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMcpKeyRouteImport } from './routes/api/public/mcp/$key'
import { Route as ApiPublicTiktokOauthCallbackRouteImport } from './routes/api/public/tiktok/oauth.callback'
import { Route as ApiPublicRdstationOauthCallbackRouteImport } from './routes/api/public/rdstation/oauth.callback'
import { Route as ApiPublicPipedriveOauthCallbackRouteImport } from './routes/api/public/pipedrive/oauth.callback'
import { Route as ApiPublicMetaOauthCallbackRouteImport } from './routes/api/public/meta/oauth/callback'
import { Route as ApiPublicLinkedinOauthCallbackRouteImport } from './routes/api/public/linkedin/oauth.callback'
import { Route as ApiPublicInstagramOauthCallbackRouteImport } from './routes/api/public/instagram/oauth/callback'
import { Route as ApiPublicGoogleOauthCallbackRouteImport } from './routes/api/public/google/oauth.callback'
import { Route as ApiPublicGaOauthCallbackRouteImport } from './routes/api/public/ga/oauth.callback'
import { Route as ApiPublicBingOauthCallbackIndexRouteImport } from './routes/api/public/bing/oauth/callback/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LpRoute = LpRouteImport.update({
  id: '/lp',
  path: '/lp',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro-empresa',
  path: '/cadastro-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRegistrationRoute = CompanyRegistrationRouteImport.update({
  id: '/Company-registration',
  path: '/Company-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrRoute = AuthenticatedPrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConexoesRoute = AuthenticatedConexoesRouteImport.update({
  id: '/conexoes',
  path: '/conexoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthTiktokCallbackRoute = AuthTiktokCallbackRouteImport.update({
  id: '/auth/tiktok/callback',
  path: '/auth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugBingAiTestRoute = ApiDebugBingAiTestRouteImport.update({
  id: '/api/debug/bing-ai-test',
  path: '/api/debug/bing-ai-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMcpKeyRoute = ApiPublicMcpKeyRouteImport.update({
  id: '/api/public/mcp/$key',
  path: '/api/public/mcp/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTiktokOauthCallbackRoute =
  ApiPublicTiktokOauthCallbackRouteImport.update({
    id: '/api/public/tiktok/oauth/callback',
    path: '/api/public/tiktok/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRdstationOauthCallbackRoute =
  ApiPublicRdstationOauthCallbackRouteImport.update({
    id: '/api/public/rdstation/oauth/callback',
    path: '/api/public/rdstation/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPipedriveOauthCallbackRoute =
  ApiPublicPipedriveOauthCallbackRouteImport.update({
    id: '/api/public/pipedrive/oauth/callback',
    path: '/api/public/pipedrive/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaOauthCallbackRoute =
  ApiPublicMetaOauthCallbackRouteImport.update({
    id: '/api/public/meta/oauth/callback',
    path: '/api/public/meta/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLinkedinOauthCallbackRoute =
  ApiPublicLinkedinOauthCallbackRouteImport.update({
    id: '/api/public/linkedin/oauth/callback',
    path: '/api/public/linkedin/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramOauthCallbackRoute =
  ApiPublicInstagramOauthCallbackRouteImport.update({
    id: '/api/public/instagram/oauth/callback',
    path: '/api/public/instagram/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleOauthCallbackRoute =
  ApiPublicGoogleOauthCallbackRouteImport.update({
    id: '/api/public/google/oauth/callback',
    path: '/api/public/google/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGaOauthCallbackRoute =
  ApiPublicGaOauthCallbackRouteImport.update({
    id: '/api/public/ga/oauth/callback',
    path: '/api/public/ga/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBingOauthCallbackIndexRoute =
  ApiPublicBingOauthCallbackIndexRouteImport.update({
    id: '/api/public/bing/oauth/callback/',
    path: '/api/public/bing/oauth/callback/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Company-registration': typeof CompanyRegistrationRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/login': typeof LoginRoute
  '/logo': typeof LogoRoute
  '/lp': typeof LpRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/pr': typeof AuthenticatedPrRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/debug/bing-ai-test': typeof ApiDebugBingAiTestRoute
  '/auth/tiktok/callback': typeof AuthTiktokCallbackRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/public/mcp/$key': typeof ApiPublicMcpKeyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/ga/oauth/callback': typeof ApiPublicGaOauthCallbackRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/instagram/oauth/callback': typeof ApiPublicInstagramOauthCallbackRoute
  '/api/public/linkedin/oauth/callback': typeof ApiPublicLinkedinOauthCallbackRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/pipedrive/oauth/callback': typeof ApiPublicPipedriveOauthCallbackRoute
  '/api/public/rdstation/oauth/callback': typeof ApiPublicRdstationOauthCallbackRoute
  '/api/public/tiktok/oauth/callback': typeof ApiPublicTiktokOauthCallbackRoute
  '/api/public/bing/oauth/callback/': typeof ApiPublicBingOauthCallbackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Company-registration': typeof CompanyRegistrationRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/login': typeof LoginRoute
  '/logo': typeof LogoRoute
  '/lp': typeof LpRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/conexoes': typeof AuthenticatedConexoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/pr': typeof AuthenticatedPrRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/blog': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/debug/bing-ai-test': typeof ApiDebugBingAiTestRoute
  '/auth/tiktok/callback': typeof AuthTiktokCallbackRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/api/public/mcp/$key': typeof ApiPublicMcpKeyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/ga/oauth/callback': typeof ApiPublicGaOauthCallbackRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/instagram/oauth/callback': typeof ApiPublicInstagramOauthCallbackRoute
  '/api/public/linkedin/oauth/callback': typeof ApiPublicLinkedinOauthCallbackRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/pipedrive/oauth/callback': typeof ApiPublicPipedriveOauthCallbackRoute
  '/api/public/rdstation/oauth/callback': typeof ApiPublicRdstationOauthCallbackRoute
  '/api/public/tiktok/oauth/callback': typeof ApiPublicTiktokOauthCallbackRoute
  '/api/public/bing/oauth/callback': typeof ApiPublicBingOauthCallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Company-registration': typeof CompanyRegistrationRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/login': typeof LoginRoute
  '/logo': typeof LogoRoute
  '/lp': typeof LpRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/conexoes': typeof AuthenticatedConexoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/pr': typeof AuthenticatedPrRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/debug/bing-ai-test': typeof ApiDebugBingAiTestRoute
  '/auth/tiktok/callback': typeof AuthTiktokCallbackRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/public/mcp/$key': typeof ApiPublicMcpKeyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/ga/oauth/callback': typeof ApiPublicGaOauthCallbackRoute
  '/api/public/google/oauth/callback': typeof ApiPublicGoogleOauthCallbackRoute
  '/api/public/instagram/oauth/callback': typeof ApiPublicInstagramOauthCallbackRoute
  '/api/public/linkedin/oauth/callback': typeof ApiPublicLinkedinOauthCallbackRoute
  '/api/public/meta/oauth/callback': typeof ApiPublicMetaOauthCallbackRoute
  '/api/public/pipedrive/oauth/callback': typeof ApiPublicPipedriveOauthCallbackRoute
  '/api/public/rdstation/oauth/callback': typeof ApiPublicRdstationOauthCallbackRoute
  '/api/public/tiktok/oauth/callback': typeof ApiPublicTiktokOauthCallbackRoute
  '/api/public/bing/oauth/callback/': typeof ApiPublicBingOauthCallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Company-registration'
    | '/cadastro-empresa'
    | '/login'
    | '/logo'
    | '/lp'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/ai'
    | '/conexoes'
    | '/dashboard'
    | '/demandas'
    | '/entregas'
    | '/pr'
    | '/profile'
    | '/schedule'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/return'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/reports/$reportId'
    | '/api/ai/chat'
    | '/api/debug/bing-ai-test'
    | '/auth/tiktok/callback'
    | '/reports/'
    | '/api/public/mcp/$key'
    | '/api/public/payments/webhook'
    | '/api/public/ga/oauth/callback'
    | '/api/public/google/oauth/callback'
    | '/api/public/instagram/oauth/callback'
    | '/api/public/linkedin/oauth/callback'
    | '/api/public/meta/oauth/callback'
    | '/api/public/pipedrive/oauth/callback'
    | '/api/public/rdstation/oauth/callback'
    | '/api/public/tiktok/oauth/callback'
    | '/api/public/bing/oauth/callback/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Company-registration'
    | '/cadastro-empresa'
    | '/login'
    | '/logo'
    | '/lp'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/ai'
    | '/conexoes'
    | '/dashboard'
    | '/demandas'
    | '/entregas'
    | '/pr'
    | '/profile'
    | '/schedule'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/return'
    | '/blog'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/reports/$reportId'
    | '/api/ai/chat'
    | '/api/debug/bing-ai-test'
    | '/auth/tiktok/callback'
    | '/reports'
    | '/api/public/mcp/$key'
    | '/api/public/payments/webhook'
    | '/api/public/ga/oauth/callback'
    | '/api/public/google/oauth/callback'
    | '/api/public/instagram/oauth/callback'
    | '/api/public/linkedin/oauth/callback'
    | '/api/public/meta/oauth/callback'
    | '/api/public/pipedrive/oauth/callback'
    | '/api/public/rdstation/oauth/callback'
    | '/api/public/tiktok/oauth/callback'
    | '/api/public/bing/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/Company-registration'
    | '/_authenticated'
    | '/cadastro-empresa'
    | '/login'
    | '/logo'
    | '/lp'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/conexoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas'
    | '/_authenticated/entregas'
    | '/_authenticated/pr'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/return'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/reports/$reportId'
    | '/api/ai/chat'
    | '/api/debug/bing-ai-test'
    | '/auth/tiktok/callback'
    | '/_authenticated/reports/'
    | '/api/public/mcp/$key'
    | '/api/public/payments/webhook'
    | '/api/public/ga/oauth/callback'
    | '/api/public/google/oauth/callback'
    | '/api/public/instagram/oauth/callback'
    | '/api/public/linkedin/oauth/callback'
    | '/api/public/meta/oauth/callback'
    | '/api/public/pipedrive/oauth/callback'
    | '/api/public/rdstation/oauth/callback'
    | '/api/public/tiktok/oauth/callback'
    | '/api/public/bing/oauth/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRegistrationRoute: typeof CompanyRegistrationRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  LoginRoute: typeof LoginRoute
  LogoRoute: typeof LogoRoute
  LpRoute: typeof LpRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiDebugBingAiTestRoute: typeof ApiDebugBingAiTestRoute
  AuthTiktokCallbackRoute: typeof AuthTiktokCallbackRoute
  ApiPublicMcpKeyRoute: typeof ApiPublicMcpKeyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicGaOauthCallbackRoute: typeof ApiPublicGaOauthCallbackRoute
  ApiPublicGoogleOauthCallbackRoute: typeof ApiPublicGoogleOauthCallbackRoute
  ApiPublicInstagramOauthCallbackRoute: typeof ApiPublicInstagramOauthCallbackRoute
  ApiPublicLinkedinOauthCallbackRoute: typeof ApiPublicLinkedinOauthCallbackRoute
  ApiPublicMetaOauthCallbackRoute: typeof ApiPublicMetaOauthCallbackRoute
  ApiPublicPipedriveOauthCallbackRoute: typeof ApiPublicPipedriveOauthCallbackRoute
  ApiPublicRdstationOauthCallbackRoute: typeof ApiPublicRdstationOauthCallbackRoute
  ApiPublicTiktokOauthCallbackRoute: typeof ApiPublicTiktokOauthCallbackRoute
  ApiPublicBingOauthCallbackIndexRoute: typeof ApiPublicBingOauthCallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp': {
      id: '/lp'
      path: '/lp'
      fullPath: '/lp'
      preLoaderRoute: typeof LpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-empresa': {
      id: '/cadastro-empresa'
      path: '/cadastro-empresa'
      fullPath: '/cadastro-empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Company-registration': {
      id: '/Company-registration'
      path: '/Company-registration'
      fullPath: '/Company-registration'
      preLoaderRoute: typeof CompanyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pr': {
      id: '/_authenticated/pr'
      path: '/pr'
      fullPath: '/pr'
      preLoaderRoute: typeof AuthenticatedPrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conexoes': {
      id: '/_authenticated/conexoes'
      path: '/conexoes'
      fullPath: '/conexoes'
      preLoaderRoute: typeof AuthenticatedConexoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/tiktok/callback': {
      id: '/auth/tiktok/callback'
      path: '/auth/tiktok/callback'
      fullPath: '/auth/tiktok/callback'
      preLoaderRoute: typeof AuthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/bing-ai-test': {
      id: '/api/debug/bing-ai-test'
      path: '/api/debug/bing-ai-test'
      fullPath: '/api/debug/bing-ai-test'
      preLoaderRoute: typeof ApiDebugBingAiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp/$key': {
      id: '/api/public/mcp/$key'
      path: '/api/public/mcp/$key'
      fullPath: '/api/public/mcp/$key'
      preLoaderRoute: typeof ApiPublicMcpKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/oauth/callback': {
      id: '/api/public/tiktok/oauth/callback'
      path: '/api/public/tiktok/oauth/callback'
      fullPath: '/api/public/tiktok/oauth/callback'
      preLoaderRoute: typeof ApiPublicTiktokOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rdstation/oauth/callback': {
      id: '/api/public/rdstation/oauth/callback'
      path: '/api/public/rdstation/oauth/callback'
      fullPath: '/api/public/rdstation/oauth/callback'
      preLoaderRoute: typeof ApiPublicRdstationOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pipedrive/oauth/callback': {
      id: '/api/public/pipedrive/oauth/callback'
      path: '/api/public/pipedrive/oauth/callback'
      fullPath: '/api/public/pipedrive/oauth/callback'
      preLoaderRoute: typeof ApiPublicPipedriveOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/oauth/callback': {
      id: '/api/public/meta/oauth/callback'
      path: '/api/public/meta/oauth/callback'
      fullPath: '/api/public/meta/oauth/callback'
      preLoaderRoute: typeof ApiPublicMetaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/oauth/callback': {
      id: '/api/public/linkedin/oauth/callback'
      path: '/api/public/linkedin/oauth/callback'
      fullPath: '/api/public/linkedin/oauth/callback'
      preLoaderRoute: typeof ApiPublicLinkedinOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/oauth/callback': {
      id: '/api/public/instagram/oauth/callback'
      path: '/api/public/instagram/oauth/callback'
      fullPath: '/api/public/instagram/oauth/callback'
      preLoaderRoute: typeof ApiPublicInstagramOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/oauth/callback': {
      id: '/api/public/google/oauth/callback'
      path: '/api/public/google/oauth/callback'
      fullPath: '/api/public/google/oauth/callback'
      preLoaderRoute: typeof ApiPublicGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ga/oauth/callback': {
      id: '/api/public/ga/oauth/callback'
      path: '/api/public/ga/oauth/callback'
      fullPath: '/api/public/ga/oauth/callback'
      preLoaderRoute: typeof ApiPublicGaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bing/oauth/callback/': {
      id: '/api/public/bing/oauth/callback/'
      path: '/api/public/bing/oauth/callback'
      fullPath: '/api/public/bing/oauth/callback/'
      preLoaderRoute: typeof ApiPublicBingOauthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedConexoesRoute: typeof AuthenticatedConexoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedPrRoute: typeof AuthenticatedPrRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedConexoesRoute: AuthenticatedConexoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedPrRoute: AuthenticatedPrRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRegistrationRoute: CompanyRegistrationRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  LoginRoute: LoginRoute,
  LogoRoute: LogoRoute,
  LpRoute: LpRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiDebugBingAiTestRoute: ApiDebugBingAiTestRoute,
  AuthTiktokCallbackRoute: AuthTiktokCallbackRoute,
  ApiPublicMcpKeyRoute: ApiPublicMcpKeyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicGaOauthCallbackRoute: ApiPublicGaOauthCallbackRoute,
  ApiPublicGoogleOauthCallbackRoute: ApiPublicGoogleOauthCallbackRoute,
  ApiPublicInstagramOauthCallbackRoute: ApiPublicInstagramOauthCallbackRoute,
  ApiPublicLinkedinOauthCallbackRoute: ApiPublicLinkedinOauthCallbackRoute,
  ApiPublicMetaOauthCallbackRoute: ApiPublicMetaOauthCallbackRoute,
  ApiPublicPipedriveOauthCallbackRoute: ApiPublicPipedriveOauthCallbackRoute,
  ApiPublicRdstationOauthCallbackRoute: ApiPublicRdstationOauthCallbackRoute,
  ApiPublicTiktokOauthCallbackRoute: ApiPublicTiktokOauthCallbackRoute,
  ApiPublicBingOauthCallbackIndexRoute: ApiPublicBingOauthCallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
